# Generated by Django 5.2.6 on 2025-10-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('aciklama', models.TextField()),
                ('malzemeler', models.TextField()),
                ('hazirlama_suresi', models.IntegerField(help_text='Dakika')),
                ('pisme_suresi', models.IntegerField(help_text='Dakika')),
                ('porsiyon_sayisi', models.IntegerField(default=1)),
                ('yayinlanma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tarif',
                'verbose_name_plural': 'Tarifler',
                'ordering': ['-yayinlanma_tarihi'],
            },
        ),
    ]
