# Generated by Django 5.2.6 on 2025-10-29 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarifler', '0002_tarif_yazar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tarif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarifler.tarif')),
            ],
            options={
                'verbose_name_plural': 'Favoriler',
                'unique_together': {('kullanici', 'tarif')},
            },
        ),
    ]
